config/routes.rb
Rails.application.routes.draw do
  # only enable /locations for now
  resources :locations, only: [:index]

  root 'locations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  serialize :vaccine_types

  # https://bigbinary.com/blog/rails-6-1-adds-nulls-first-and-nulls-last-to-arel
  scope :sort_by_last_available, -> { order(Location.arel_table[:last_available_at].desc.nulls_last) }

  def portal
    PortalsHelper.find_by_key(portal_key)
  end

  def parsed_appointments_by_date
    parsed_appointments = Array(appointments).map do |appointment|
      appointment_time_zone = appointment["time_zone"] || time_zone
      date = DateTime.parse(appointment["time"])
      if appointment_time_zone
        date = date.in_time_zone(appointment_time_zone)
      end
    end.sort

    parsed_appointments.group_by do |appointment|
      appointment.at_beginning_of_day
    end
  end
end

app/models/portals/test_portal.rb
class Portals::TestPortal < Turbovax::Portal
  name "Gotham City Clinic"
  key "gotham_city"
  public_url "https://www.turbovax.info/"
  api_url "http://api.turbovax.info/v1/test.json"
  api_url_variables do
    data_fetcher_params
  end
  request_http_method Turbovax::Constants::GET_REQUEST_METHOD
  notes "This is a test portal and does not require pre-registration."

  parse_response do |response|
    response_json = JSON.parse(response)
    Array(response_json["appointments"]).map do |location_json|
      appointments = Array(location_json["slots"]).map do |appointment_string|
        {
          time: DateTime.parse(appointment_string)
        }
      end

      Turbovax::Location.new(
        name: location_json["clinic_name"],
        full_address: location_json["address"],
        portal_id: location_json["clinic_id"],
        time_zone: "America/New_York",
        data: {
          vaccine_types: [location_json["vaccine"]],
          appointments: appointments,
        }
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy ]

  # GET /locations or /locations.json
  def index
    @locations = Location.sort_by_last_available
  end

  # GET /locations/1 or /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: "Location was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: "Location was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:uuid, :name, :address, :area, :enabled, :portal_key, :portal_uuid, :latitude, :longitude, :last_available)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
  include Rails.application.routes.url_helpers

  def self.format_appointment_date(date)
    date.strftime("%a, %-m/%-e")
  end

  def self.format_appointment_time(date)
    date.strftime("%-l:%M%p")
  end

  def self.google_maps_url(address)
    "https://www.google.com/maps/search/#{address}"
  end

  def self.enable_reserve_button?(location)
    location.appointment_count.positive?
  end

  def self.last_updated(locations)
    last_updated = locations.map(&:updated_at).max
    last_updated.presence && last_updated.strftime("%b %-e %-l:%M%p")
  end

  def self.total_appointments(locations)
    locations.map(&:appointment_count).sum
  end

  def self.total_locations(locations)
    locations.select { |location| location.appointment_count.positive? }.size
  end
end

app/helpers/portals_helper.rb
module PortalsHelper
  ALL_PORTALS = [
    Portals::TestPortal,
  ].freeze

  PORTALS_BY_KEY = ALL_PORTALS.each_with_object({}) do |portal, memo|
    memo[portal.key] = portal
  end.freeze

  def self.find_by_key(key)
    PORTALS_BY_KEY[key]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbovax</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uuid %>
    <%= form.text_field :uuid %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.text_field :area %>
  </div>

  <div class="field">
    <%= form.label :enabled %>
    <%= form.check_box :enabled %>
  </div>

  <div class="field">
    <%= form.label :portal_key %>
    <%= form.text_field :portal_key %>
  </div>

  <div class="field">
    <%= form.label :portal_uuid %>
    <%= form.text_field :portal_uuid %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :last_available %>
    <%= form.date_select :last_available %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div class="card">
  <h2><%= "#{location.name} [#{location.portal.name}]" %></h2>
  <%= button_to "Reserve", location.portal.public_url, method: :get, disabled: !LocationsHelper.enable_reserve_button?(location) %>
  <h4><%= link_to location.full_address, LocationsHelper.google_maps_url(location.full_address), target: "_blank" %></h4>
  <% if location.vaccine_types.present? %>
  <div>
    Vaccine Type: <%= Array(location.vaccine_types).to_sentence %>
  </div>
  <% end %>
  <% if location.last_available_at.present? %>
    <p>Last available: <%= time_ago_in_words(location.last_available_at) %></p>
  <% end %>
  <% if location.portal.notes.present? %>
    <p>Note: <%= location.portal.notes %></p>
  <% end %>
  <hr>
  <div>
    <div class="appointments-block">
      <% location.parsed_appointments_by_date.each do |day, appointments| %>
        <div>
          <span class="appointment-date"><%= LocationsHelper.format_appointment_date(day) %></span>
          <% appointments.each do |appointment| %>
            <span class="appointment"><%= LocationsHelper.format_appointment_time(appointment) %></span>
          <% end %>
        </div>
      <% end %>
      </div>
    </div>
</div>

app/views/locations/_summary.html.erb
<div class="summary">
  <div class="half">
  <h3>Last Updated</h3>
  <%= LocationsHelper.last_updated(@locations) %>
  </div>
  <div class="half">
  <h3>Appointments</h3>
  <%= pluralize(LocationsHelper.total_appointments(@locations), "appointment") %> at <%= pluralize(LocationsHelper.total_locations(@locations), "location") %>
  </div>
</div>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Very Own TurboVax</h1>
<%= render partial: "summary", locations: @locations %>
<%= render partial: "location", collection: @locations %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @location.uuid %>
</p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Full Address:</strong>
  <%= @location.full_address %>
</p>

<p>
  <strong>Area:</strong>
  <%= @location.area %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @location.enabled %>
</p>

<p>
  <strong>Portal key:</strong>
  <%= @location.portal_key %>
</p>

<p>
  <strong>Portal id:</strong>
  <%= @location.portal_id %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<p>
  <strong>Timezone:</strong>
  <%= @location.time_zone %>
</p>

<p>
  <strong>Last available:</strong>
  <%= @location.last_available %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>